swagger: "2.0"
info:
  title: NeteaseCloudMusic Api
  description: 用golang写的网易云音乐API,请多多指教
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /user/cellphonelogin:
    get:
      tags:
      - user
      description: Logs user into the system
      operationId: UserController.CellphoneLogin
      parameters:
      - in: query
        name: phone
        description: The phone    for login
        required: true
        type: string
      - in: query
        name: password
        description: The password for login
        required: true
        type: string
      responses:
        "200":
          description: '{string} login success'
        "400":
          description: param error
        "500":
          description: Program error
        "501":
          description: Account number does not exist
        "502":
          description: Password error
  /user/detail:
    get:
      tags:
      - user
      description: get user detail
      operationId: UserController.detail
      parameters:
      - in: query
        name: uid
        description: The uid for user detail
        required: true
        type: string
      responses:
        "200":
          description: '{string} get user detail success'
  /user/playlist:
    get:
      tags:
      - user
      description: get user playlist
      operationId: UserController.playlist
      parameters:
      - in: query
        name: uid
        description: The uid for user playlist
        required: true
        type: string
      responses:
        "200":
          description: '{string} get playlist success'
tags:
- name: user
  description: |
    Operations about User
